services:
  api:
    image: mariannatests-api
    build:
      context: ./api
      target: api-dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    env_file:
      - ./api/.env
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
