services:
  api:
    image: marianna-tests-api
    build:
      context: ./api
      target: api-dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/api
      - /api/.venv/ # This excludes the virtual environment directory
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/assessments
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  client:
    build:
      context: ./client
      target: client-dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/local/api
      - /usr/local/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev
    depends_on:
      - api
    networks:
      - app-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-assessments}
    env_file:
      - ./api/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "assessments"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
