# To run tests, use one of these commands:
#
# Run all tests (default):
#   docker compose -f docker-compose.test.yml up --build
#
# Run with coverage:
#   docker compose -f docker-compose.test.yml run --rm api-test pytest --cov=assessments tests/
#
# Run specific test file:
#   docker compose -f docker-compose.test.yml run --rm api-test pytest tests/unit/models/test_assessment.py -v
#
# Run tests matching a pattern:
#   docker compose -f docker-compose.test.yml run --rm api-test pytest -v -k "test_create"
#
# Run tests with detailed output:
#   docker compose -f docker-compose.test.yml run --rm api-test pytest -vv
#
# Run tests and stop on first failure:
#   docker compose -f docker-compose.test.yml run --rm api-test pytest -x
#
# Run tests with JUnit report (useful for CI):
#   docker compose -f docker-compose.test.yml run --rm api-test pytest --junitxml=test-results.xml

services:
  api-test:
    build:
      context: ./api
      target: api-test
    volumes:
      - ./api:/api
      - /api/.venv/
    env_file:
      - ./api/.env
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      DATABASE_URL: "postgresql://postgres:postgres@db-test:5432/test_db"
      PYTHONPATH: /api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    depends_on:
      db-test:
        condition: service_healthy
    networks:
      - test-network
    command: pytest -v
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-test:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    ports:
      - "5433:5432" # Different port to avoid conflicts with dev database
    networks:
      - test-network
    tmpfs:
      - /var/lib/postgresql/data # Use tmpfs for faster testing
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  test-network:
    name: test-network
    driver: bridge
