services:
  api:
    image: mariannatests-api
    build:
      context: ./api
      target: api-dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
      - /app/.venv/  # This excludes the virtual environment directory
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    env_file:
      - ./api/.env
    depends_on:
      - db
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
