"""add assessment diagnostics

Revision ID: 622c6317872f
Revises: 612046dd75c1
Create Date: 2025-03-06 16:34:39.911713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '622c6317872f'
down_revision: Union[str, None] = '612046dd75c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('min_value', sa.Float(), nullable=True),
                    sa.Column('max_value', sa.Float(), nullable=True),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('assessment_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['assessment_id'], ['assessment.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnostic')
    # ### end Alembic commands ###
